// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SME.Pedagogico.Relatorios.Contexts;

namespace SME.Pedagogico.Relatorios.Migrations
{
    [DbContext(typeof(SmeReportsContext))]
    [Migration("20190408173902_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SME.Pedagogico.Relatorios.Models.Application", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("DigitalSignature");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("SME.Pedagogico.Relatorios.Models.LogControl", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("ModifiedAt");

                    b.Property<string>("ModifiedBy");

                    b.HasKey("Id");

                    b.ToTable("LogControls");
                });

            modelBuilder.Entity("SME.Pedagogico.Relatorios.Models.Report", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationId");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb");

                    b.Property<string>("LogControlId");

                    b.Property<string>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("LogControlId");

                    b.HasIndex("TypeId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SME.Pedagogico.Relatorios.Models.ReportTag", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ReportId");

                    b.Property<string>("TagId");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("TagId");

                    b.ToTable("ReportTags");
                });

            modelBuilder.Entity("SME.Pedagogico.Relatorios.Models.ReportType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ReportTypes");
                });

            modelBuilder.Entity("SME.Pedagogico.Relatorios.Models.Tag", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SME.Pedagogico.Relatorios.Models.Report", b =>
                {
                    b.HasOne("SME.Pedagogico.Relatorios.Models.Application", "Application")
                        .WithMany("ReportList")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("SME.Pedagogico.Relatorios.Models.LogControl", "LogControl")
                        .WithMany("ReportList")
                        .HasForeignKey("LogControlId");

                    b.HasOne("SME.Pedagogico.Relatorios.Models.ReportType", "Type")
                        .WithMany("ReportList")
                        .HasForeignKey("TypeId");
                });

            modelBuilder.Entity("SME.Pedagogico.Relatorios.Models.ReportTag", b =>
                {
                    b.HasOne("SME.Pedagogico.Relatorios.Models.Report", "Report")
                        .WithMany("Tags")
                        .HasForeignKey("ReportId");

                    b.HasOne("SME.Pedagogico.Relatorios.Models.Tag", "Tag")
                        .WithMany("ReportTagList")
                        .HasForeignKey("TagId");
                });
#pragma warning restore 612, 618
        }
    }
}
